blog/urls.py
from django.conf.urls import url
from . import views as blog_views

urlpatterns = [
    url(r'^(?P<id>[\w-]+)/$', blog_views.blog, name='blog'),
    url(r'^comment/(?P<blog_id>[\w-]+)/$', blog_views.post_comment, name='comment'),
    url(r'^notification/(?P<id>[\w-]+)/$', blog_views.blog_notification, name='notification'),
    url(r'^subscribe/(?P<blog_id>[\w-]+)/$', blog_views.subscribe, name='subscribe'),
    url(r'^reply/(?P<blog_id>[\w-]+)/(?P<comment_id>[\w-]+)/$', blog_views.comment_reply, name='reply'),
]

source/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from courses import views as course_views
from registration.backends.default.views import RegistrationView
from users.forms import AddUser

urlpatterns = [
    url(r'^$', user_views.home, name='home'),
    url(r'^ourteam/$', user_views.ourteam, name='ourteam'),
    url(r'^about/$', user_views.about, name='about'),
    url(r'^contact/$', user_views.contact, name='contact'),
    url(r'^logout_view/$', user_views.logout_view, name='logout_view'),
    url(r'^thanks$',course_views.thanks, name='thanks'),
    url(r'cancel$', course_views.cancel, name='cancel'),	
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls')),
    url(r'^apptours/', include('apptours.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^profile/', include('users.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('', include('social_django.urls', namespace='social')),
]

# Remove this in project deployment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings

class BlogPost(models.Model):
    title = models.CharField("Title", max_length=300,)
    details = models.TextField("Details", null=True, blank=True)
    date_created = models.DateTimeField(null=True, blank=True)
    created_by = models.CharField("author", default="OpenBuild Team", max_length=100,)


def attachment_path(instance, filename):
    """
    Provide a file path that will help prevent files being overwritten, by
    putting attachments in a folder off attachments for ticket/followup_id/.
    """
    import os
    from django.conf import settings
    os.umask(0)
    path = 'blog/attachments/%s' % (instance.blog.id )
    att_path = os.path.join(settings.MEDIA_ROOT, path)
    if settings.DEFAULT_FILE_STORAGE == "django.core.files.storage.FileSystemStorage":
        if not os.path.exists(att_path):
            os.makedirs(att_path, 0o777)
    return os.path.join(path, filename)

class BlogAttachment(models.Model):
    blog = models.ForeignKey(BlogPost,verbose_name=('blog'),)
    file = models.FileField(_('File'),upload_to=attachment_path, max_length=1000,)
    filename = models.CharField(_('Filename'),max_length=1000,)
    mime_type = models.CharField(_('MIME Type'),max_length=255,)
    size = models.IntegerField(_('Size'),help_text=_('Size of this file in bytes'),)

    def get_upload_to(self, field_attname):
        """ Get upload_to path specific to this item """
        if not self.id:
            return u''
        return u'blog/attachments/%s' % (
            
            self.task.id
            )

    def __unicode__(self):
        return u'%s' % self.filename

    class Meta:
        ordering = ['filename',]
        verbose_name = _('Attachment')
        verbose_name_plural = _('Attachments')


class BlogComment(models.Model):
	blog_id = models.ForeignKey(BlogPost,related_name=('blog_comments'),)
	comment = models.CharField("Comment", max_length=500,)
	created_by = models.CharField("Sender", default="Anonymous", max_length=100,)
	sender_email = models.EmailField("Sender email ", blank=True, null=True,)
	posted_date = models.DateTimeField(null=True, blank=True)

 
class Response(models.Model):
	blog_id = models.ForeignKey(BlogPost,related_name=('response'),)
	comment_id = models.ForeignKey(BlogComment,related_name=('reply'),)
	reply = models.CharField("Response", max_length=500,)
	created_by = models.CharField("Sender", default="Anonymous", max_length=100,)
	sender_email = models.EmailField("Sender email ", blank=True, null=True,)
	posted_date = models.DateTimeField(null=True, blank=True)

class BlogSubscription(models.Model):
    email = models.EmailField("subscriber email ", null=True,)

users/forms.py
from django import forms
from users.models import *


class AddUser(forms.ModelForm):
    class Meta:
        model = UserProfile
        widgets = {
            'password': forms.PasswordInput(),
        }
        fields = ['username', 'password', 'email', 'is_professor', 'is_site_admin']


class EditUser(forms.ModelForm):
    class Meta:
        model = UserProfile
        widgets = {
            'password': forms.PasswordInput(),
        }
        fields = ['username', 'password', 'email', 'is_professor', 'is_site_admin']

    # Don't want to modify blank setting inside models (doing so will break normal validation in admin site)
    # The redefined constructor won't harm any functionality.
    def __init__(self, *args, **kwargs):
        super(EditUser, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = False


class Contact(forms.Form):
    sender = forms.CharField(label='Name', max_length=30)
    subject = forms.CharField(label='Subject', max_length=30)
    email = forms.EmailField(label='Email', max_length=30)
    message = forms.CharField(widget=forms.Textarea)

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OpenBuild</title>
  {% include 'head_css.html' %}
  {% include 'javascript.html' %}
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top" class="banner-back">


<!-- Wrap all page content here -->
<div>

  <!-- Begin page content -->
  {% include 'navbar.html' %}

  {% include 'app_tour/app_tour_modal.html' %}

  <div class="row social_buttons sidebar-wrap"> 
      <a href="https://twitter.com/open_build" target="_blank" class="btn btn-social-icon btn-twitter">
          <span class="fa fa-twitter"></span>
       </a>
       <a href="https://www.facebook.com/OpenBuildSTEM" class="btn btn-social-icon btn-facebook" target="_blank" >
          <span class="fa fa-facebook"></span>
       </a>
       <a href="https://www.linkedin.com/company-beta/16227629/" target="_blank" class="btn btn-social-icon btn-linkedin">
          <span class="fa fa-linkedin-square"></span>
       </a>

  </div>
  <br/>

  {% block content %}
  {% endblock %}

</div>


<div class="col-md-12" id="footer">
  <div class="container">
    <a href="https://github.com/open-build" target="_blank" class="font1">© 2018 OpenBuild</a>
  </div>
</div>
</body>



<script>tinymce.init({
    selector: 'textarea',
    paste_data_images: true,
    plugins: ["image paste"],
    resize: false
  });
</script>

</html>

templates/breadcrumb.html
{% load staticfiles %}

<!-- Breadcrumb core css -->
<link href="{% static "css/breadcrumb.css" %}" rel="stylesheet"/>
<br/>
<br/>
<div class="bread-h">
  <div class="container">
    <section class="title-section">
      <h1 >{{ title }} </h1>
      <ul class="breadcrumb breadcrumb__t">

        <li>
          <a href="/">Home&nbsp</a>
          {% if  path  != None %}
            {% url 'forum' as forum_url %}
            {% if request.get_full_path != forum_url %}
              <span class="spacing-path">&nbsp/&nbsp&nbsp</span><a href="/{{ redirect_path }}">&nbsp{{ path }}&nbsp</a>
            {% endif %}
          {% endif %}
        </li>

        {% url 'student_course' course_name slug as student_course_url %}
        {% if request.get_full_path ==  student_course_url %}
          <li><a href="{% url 'courses' %}">Courses</a></li>
        {% endif %}

        {% url 'chapter' course_name slug as chapter_url %}
        {% if request.get_full_path ==  chapter_url %}
          <li><a href="{% url 'professor_course' course_name %}">{{ course_name }}</a></li>
        {% endif %}

        {% url 'edit_txt' course_name slug text_id as chapter_url %}
        {% if request.get_full_path ==  chapter_url %}
          <li><a href="{% url 'chapter' course_name slug %}">{{ course_name }}</a></li>
        {% endif %}

        {% url 'edit_chapter' course_name chapter_id as chapter_url %}
        {% if request.get_full_path ==  chapter_url %}
          <li><a href="{% url 'professor_course' course_name %}">{{ course_name }}</a></li>
        {% endif %}

        {% url 'edit_link' course_name slug yt_id as chapter_url %}
        {% if request.get_full_path ==  chapter_url %}
          <li><a href="{% url 'chapter' course_name slug %}">{{ course_name }}</a></li>
        {% endif %}

        <li class="active">&nbsp{{ title }}</li>
      </ul>
    </section>
  </div>
</div>

templates/cancel.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<link href="{% static "css/ourteam.css" %}" rel="stylesheet" />
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
            <div class="clear-fix"></div>
                <div class="main_intro col-md-12 row">
                  <div class="col-md-1"> </div>
                  <div class="col-md-11">
                    <h2>OUR TEAM</h2>
                    <p class="our_team "><img src="{% static '/static/img/mombasa-team.jpg' %}" align="left" style="height:210px; margin-right:10px;"> The OpenBuild team is comprised of mentors, educators, and industry professionals that focus on technology solutions for international development. Our team is made up of three distinct roles that play either a Technical or Support function. The technical function consists of software engineers and developers while the support functions consists of data specialists, data analysts, and software support specialists. Each team will collaborate and work together on a particular client's needs including ensuring the server is up and running efficiently, the integrations are working well, and the support tickets are being answered in a timely manner. In addition, these teams will coordinate with the larger open source community to make sure any bounty tickets or enhancements are addressed and prioritized as well as providing training and support for issues.</p>
                  </div>
                </div>
                <!----start-content---->
                <div class="featured_content  col-md-12" id="feature">

                      <div class="col-md-3 feature_grid2" style=" border-right: 1px solid #E6E6E6;">
                        <br><h4><a href="#"><font class="feature_grid_f"> <i class="fa fa-cogs"></i> Developer</font></a></h4>
                        <p class="m_2 about_content">A software developer will be assigned to maintain the internal workings of the hosted service. For a system like TolaData that may include log rotating and monitoring, ticket tracking for bugs and enhancements as well as initial setup and migration of existing platforms.</p>
                      </div>

                      <div class="col-md-4 feature_grid2" style=" border-right: 1px solid #E6E6E6;">
                        <br><h4><a href="#"><font class="feature_grid_f"><i class="fa fa-line-chart"></i> Specialist/Analyst </font></a></h4>
                        <p class="m_2 about_content">A trainer, and data specialist will also be assigned to ensure any questions around the business process, reporting needs, data collection, and analysis are being met. They will work with clients to configure the platform to the client’s needs and help gather additional functional requirements that are not met by the current system and provide guidance on possible solutions.</p>
                      </div>

                      <div class="col-md-5 feature_grid2">
                        <br><h4><a href="#"><font class="feature_grid_f"><i class="fa fa-question-circle-o"></i> Support </font></a></h4>
                        <p class="m_2 about_content">A support specialist will be assigned to work with the client on working through any issues or enhancement requests that arise during the setup and configuration phase. In addition, the support team member will help evaluate requests and determine if technical assistance is required as well as overlap with the Analyst/Specialist role where needed.</p>
                      </div>
                </div>

                <div class="col-lg-8 col-lg-offset-2">
                  <a href="#currentprofiles" class="btn btn-circle page-scroll">
                      <i class="fa fa-angle-double-down animated"></i>
                  </a>
                </div>

            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="currentprofiles" class="content-section profile_about text-center">
                <div class="profile-section">
                    <h2>CURRENT PROFILES</h2>

                  <div class="container">
                    <div class="row col-md-12">
                      <div class="col-md-4 prof">
                          <img src="{% static '/static/img/greg.png' %}" alt="..." class="img-circle" width="120" height="120"><br>
                          <P>Greg Lind</P>
                          <P>Co-founder, Software Developer Lead</P>
                          <P>Berlin, Germany</P>
                      </div>
                      <div class="col-md-4 prof">
                        <img src="{% static '/static/img/Andrew.jpg' %}" alt="..." class="img-circle" width="120" height="120"><br>
                        <P>Andrew Pham</P>
                        <P>Co-founder, Implementation Lead</P>
                        <P>Berlin, Germany</P>
                      </div>
                      <div class="col-md-4 prof">
                        <img src="{% static '/static/img/peter.jpg' %}" alt="..." class="img-circle" width="120" height="120"><br>
                        <P>Peter Odeny</P>
                        <P>Software Developer</P>
                        <P>Nairobi, Kenya</P>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-md-4 prof">
                          <img src="{% static '/static/img/Anne.jpg' %}" alt="..." class="img-circle" width="120" height="120"><br>
                          <P>Anne Gichira</P>
                          <P>Software Developer</P>
                          <P>Nairobi, Kenya</P>
                      </div>
                      <div class="col-md-4 prof">
                        <img src="{% static '/static/img/Diego.png' %}" alt="..." class="img-circle" width="120" height="120"><br>
                        <P>Diego Borchers</P>
                        <P>Software Developer and Development Operations</P>
                        <P>Bilbao, Spain</P>
                      </div>
                      <div class="col-md-4 prof">
                        <img src="{% static '/static/img/OpenBuild-Logo-Big.png' %}" alt="..." class="img-circle" width="120" height="120"><br>
                        <P>Karrla Sandstrom</P>
                        <P>Senior Support and Implementation</P>
                        <P>Portland, Oregon USA</P>
                      </div>
                    </div>
                </div>
        </div>
    </section>

    <!-- Download Section -->
    <section id="internship" class="content-section-prof">
        <div class="profile-section">
            <div class="container">
                <div class="main_intro col-md-12 row">
                  <div class="col-md-1"> </div>
                  <h2  class="font2" >Internship</h2>
                  <p class="our_team">As part of the OpenBuild STEM and Open Source software initiatives we bring on 2-3 new volunteers or interns each year to both learn our existing infrastructure and support clients of either TolaData or OpenBuild, but to also learn from more senior developers and educators about best practices within the industry.  
                  </p>
                  <p class="our_team">We are current looking for interns, remote or located in Portland, OR; Nairobi, Kenya; or Ho Chi Minh City, Vietnam to work on open source projects and help set up STEM related activities. We have two types of Intern roles we are looking for:</p>
                </div>
                <!--start-content-->

                <div class="col-md-4 feature_grid1" style=" border-right: 1px solid #E6E6E6;">
                  <br><h4 class="text-center"><a href="#"><font class="feature_grid_f"><i class="fa fa-cogs"></i> Software Intern </font></a></h4>
                  <p class="m_2">Contribute to one of our existing Open Source projects that will benefit International Aid organizations and/or help manage large public data sets.  Work as part of the R&D team being mentored by a senior software developer to ensure the project is evolving, getting adopted by the community, and continually tested and debugged.</p>
                </div>

                <div class="col-md-4 feature_grid1" style=" border-right: 1px solid #E6E6E6;">
                  <br><h4 class="text-center"><a href="#"><font class="feature_grid_f"><i class="fa fa-desktop"></i> Hardware Intern</font></a></h4>
                  <p class="m_2">Contribute to an Open Source hardware project to help build STEM labs for middle school to high school age kids.  This can include building online lesson plans, software and hardware tests, and YouTube videos of the complete project steps.  When the physical locations open in Fall 2017 these will be used for classes in each of the spaces.</p>
                </div>

                <div class="col-md-4 feature_grid1">
                  <br><h4 class="text-center" ><a href="#"><font class="feature_grid_f"><i class="fa fa-question-circle-o"></i> More Opportunities</font></a></h3>
                  <p class="m_2">We have some additional opportunities as volunteers and each of these positions are unpaid but can evolve into part or full time paid positions with OpenBuild or one of our partner organizations.</p>
                </div>
                <div class="col-md-12"><p class="our_team">
                <br>
                To apply, please contact us at: <a href=""><font class="intern_apply"><span class="glyphicon glyphicon-envelope"></span> intern@open.build</font></a> by sending a link to your CV, LinkedIn or anything else that can give us an idea about who you are, what you do, and why you want to work with us.</p><br><br></div>

              </div>
                
            </div>
    </section>

{% endblock %}

templates/head_css.html
{% load staticfiles %}

<!-- Bootstrap core css -->
<link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet" />
<link href="{% static "css/bootstrap-tour.min.css" %}" rel="stylesheet" />
<!-- site core css -->
<link href="{% static "css/site.css" %}" rel="stylesheet" />
<!-- Base core css -->
<link href="{% static "css/base.css" %}" rel="stylesheet" />
<!-- Home page core css -->
<link href="{% static "css/home.css" %}" rel="stylesheet" />
<link href="{% static "css/contact.css" %}" rel="stylesheet" />
<link href="{% static "css/bootstrap-social.css" %}" rel="stylesheet">


<!-- Font-Awesome core css-->
<link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" />

<!--App Tour css-->
<link href="{% static "css/app_tour/app_tour.css" %}" rel="stylesheet" />

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<link href="{% static "css/contact.css" %}" rel="stylesheet" />
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container"><!-- 
            <div class="clear-fix"></div> -->
                <div class="row image">
                        <!----start-banner---->
                        <div class="text-center">
                          <div class="col-md-3 banner-img">
                            &nbsp;
                          </div>
                          <div class="col-md-6 banner-img">
                            <img src="{% static '/static/img/OpenBuild-Logo-Big.png' %}" border="1" vspace="10">
                          </div>

                        </div>

                </div>
                <div class="main_intro col-md-12 row">
                <div class="col-md-1"></div>
                  <p class="font1 col-md-10" >OpenBuild is a nonprofit organization that builds, tests, supports and teaches about Open Source software and hardware projects. Our mission is to distribute and promote Open Source software for education, nonprofit, and business use cases in underserved communities around the world.

                </div>
                <!--start-content-->
                <div class="featured_content col-md-12" id="feature">

                      <div class="col-md-4 feature_grid1" style=" border-right: 1px solid #E6E6E6;">
                        <h3 class="m_1"><a href="#opensource"><i class="icon1"> </i><br>Open Source</a></h3>
                        <p class="m_2">OpenBuild helps to build and support new and existing Open Source software for nonprofit organizations and social businesses</p>
                      </div>

                      <div class="col-md-4 feature_grid1" style=" border-right: 1px solid #E6E6E6;">
                        
                        <h3 class="m_1"><a href="#humanitarian"> <i class="icon2"> </i> <br> Data Certification</a></h3>
                        <p class="m_2">We are working with industry leaders to help define and create new security policies and privacy standards for humanitarian data sets.</p>
                      </div>

                      <div class="col-md-4 feature_grid1">
                        <h3 class="m_1"><a href="#stem"><i class="icon3"> </i><br>STEM Teaching</a></h3>
                        <p class="m_2">We are deeply passionate about contributing to the spread of learning and knowledge of Open Source technologies</p>
                      </div>
                </div>

                <div class="col-md-8 col-md-offset-2">
                  <a href="#toladata" class="btn btn-circle page-scroll">
                      <i class="fa fa-angle-double-down animated"></i>
                  </a>
                </div>

            </div>
        </div>
    </header>

    <!-- What we do Section -->
    <div id="opensource" class="container content-section toladata_about">
    <div class="main_frame">
        <div class="inner_frame col-md-12">
            <div class="col-md-10 col-md-offset-1">
                <h2 class="font2">Open Source</h2>
                <p>At its core work, OpenBuild helps to build and support new and existing Open Source software for nonprofit organizations and social businesses working in the humanitarian and development sector. 
               </p>
                <img src="{% static '/static/img/mombasa-team.jpg' %}" align="left" style="max-height:200px; margin-right:15px">
               <p>This includes supporting the development and implementation of a Open Source  data management platforms</p>
                <p>Our teams of two or more provide dedicated support to clients that either directly contract us to support their data management process and host their Open Source projects/systems or subcontract us through one of our partner Open Source projects.</p>
                <p>In addition to our Open Source projects, OpenBuild has two initiatives that promote the use of open data standards and technologies.</p>
            </div>
        </div>
    </div>
</div>
    <section id="humanitarian" class="container content-section ">
    <div class="main_frame">
        <div class="inner_frame col-md-12">
            <div class="col-md-10 col-md-offset-1">
                <h2 class="font2">Humanitarian Data Certification</h2>
                <p>We are working with industry leaders to help define and create new security policies and privacy standards for humanitarian data sets.</p> 
                <p>In this process, we will set up a new certification board that act as a certification authority for OpenBuild. In this capacity, the board will develop a process for certifying a particular type of organization, service provider or tool as having adopted the OpenBuild security and privacy standards.</p>  
               <p>This recognized certification will allow us to create standard auditing procedures and practices inside networked organization, cloud services or tools for securing information, cleaning and anonymizing beneficiary data and helping to prevent intrusions, and raising awareness of security needs.</p>  
               <p>In addition, we will help to define and continually evolve information security practices and give organizations both large and small a start in protecting themselves and their valuable data.</p> 
            </div>
        </div>
    </div>
    </section>

    <section id="stem" class="container content-section stem_about">
    <div class="main_frame">
        <div class="inner_frame main_frame1 col-md-12">
            <div class="col-md-10 col-md-offset-1">
                <h2 class="font2">STEM Teaching</h2>
                <p>With OpenBuild being an active member in the Open Source community, we are deeply passionate about contributing to the spread of learning and knowledge of Open Source technologies, both software and hardware in our local communities. </p>
                <img src="{% static '/static/img/a2.jpg' %}" align="right" style="max-height:200px; margin-left:15px">
                <p>Our developers, technical specialists, and analysts volunteer their time to work with local organizations and schools and organizations to teach STEM based courses.</p>
              <p>In addition, we partner with local community members to help set up project spaces, offer master classes and open courseware as well as introduce projects that attempt to solve real-life challenges through STEM teaching. </p>
              <p>All of these focus on Open Source software and hardware initiatives as well teaching and mentoring students and junior team members about process, best practices and more in the evolving tech industry.</p>   
              <p> For more information on ways to get involved with our STEM Teaching program, please contact us at: <a href="#">info@open.build</a></p> 

            </div>
        </div>
    </div>
    </section>
    <!-- end what we do section -->

    <!-- Contact Section -->

    <section id="contact" class="container content-section text-center">

        <div class="col-xs-12  col-md-6 col-md-offset-3">
          {% if messages %}
            <script>
            window.location.hash = '#contact';
            </script>
            {% for message in messages %}
              <p{% if message.tags %} class="alert alert-success"{% endif %}>{{ message }}</p>
            {% endfor %}
          {% endif %}
        </div>

        <div class="form-style-6">
          <h1>Contact Us</h1>
          <form method="POST" action="{% url 'users.views.contact' %}">
            {% csrf_token %}
                <input type="text" id="id_sender" maxlength="30" name="sender" placeholder="Your Name" />
                <input type="text" id="id_subject" maxlength="30" name="subject" placeholder="Subject" />
                <input type="email" id="id_email" maxlength="30" name="email" placeholder="Email Address" />
                <textarea id="id_message" name="message" placeholder="Type your Message"></textarea>
                <input type="submit" value="Send" />
          </form>
    </div>
    </section>

  <hr/>
  <div class="row col-md-12 text-center" style="margin-bottom:40px">
    <div class="col-md-3">
      <h4><a href="https://openbuild.hackpad.com">Our Ideas!</a></h4>
    </div>
  </div>

{% endblock %}

templates/javascript.html
{% load staticfiles %}

<script src="{% static 'js/jquery-2.2.2.min.js' %}" rel="script"></script>
<script src="{% static 'js/tinymce/tinymce.min.js' %}" rel="script"></script>

<!-- Bootstrap core js -->
<script src="{% static 'js/bootstrap.min.js' %}" rel="script"></script>
<script src="{% static 'js/bootstrap-tour.min.js' %}" rel="script"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

<!--setting up app tours-->
<script src="{% static 'js/app_tour/apptour.js'%}" rel="script"></script>
<script src="{% static 'js/app_tour/tour_controller.js'%}" rel="script"></script>
<script src="{% static 'js/app_tour/admin_tours_view.js'%}" rel="script"></script>
<script src="{% static 'js/app_tour/create_tour_form.js'%}" rel="script"></script>
<script src="{% static 'js/app_tour/display_tours.js'%}" rel="script"></script>
<script src="{% static 'js/app_tour/generate_tour_step.js'%}" rel="script"></script>
<script src="{% static 'js/app_tour/apptour_main.js'%}" rel="script"></script>

<!-- Bootstrap core js -->
<script src="{% static "js/jquery.easing.min.js" %}" rel="script"></script>
<!-- site js -->

templates/sidebar.html
<div id="sidebar-wrapper">
	<ul class="sidebar-nav">
		{% if queryset %}
			{% for instance in queryset %}
				{{ instance.chapter_name}}
			{% endfor %}
		{% endif %}
    </ul>
</div>

templates/thanks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<link href="{% static "css/ourteam.css" %}" rel="stylesheet" />
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
            <div class="clear-fix"></div>
                <div class="main_intro col-md-12 row">
                  <div class="col-md-1"> </div>
                  <div class="col-md-11">
                    <h2>THANK YOU!</h2>
                    <p class="our_team "><img src="{% static '/static/img/mombasa-team.jpg' %}" align="left" style="height:210px; margin-right:10px;"> The OpenBuild team is comprised of mentors, educators, and industry professionals that focus on technology solutions for international development. Our team is made up of three distinct roles that play either a Technical or Support function. The technical function consists of software engineers and developers while the support functions consists of data specialists, data analysts, and software support specialists. Each team will collaborate and work together on a particular client's needs including ensuring the server is up and running efficiently, the integrations are working well, and the support tickets are being answered in a timely manner. In addition, these teams will coordinate with the larger open source community to make sure any bounty tickets or enhancements are addressed and prioritized as well as providing training and support for issues.</p>
                  <h3>Thanks for supporting STEM and Education</h3>
</div>
                </div>

            </div>
        </div>
    </header>


{% endblock %}