apptours/urls.py
from django.conf.urls import url
from . import views as apptours_views

urlpatterns = [
    url(r'^get_tours$', apptours_views.get_tours, name='get_tours'),
    url(r'^mark_tour_as_visited/(\d+)/$', apptours_views.mark_tour_as_visited, name='mark_tour_as_visited'),
    url(r'^create_apptour', apptours_views.create_apptour, name='create_apptour'),
    url(r'^create_tour', apptours_views.create_tour, name='create_tour'),
    url(r'^view_tours', apptours_views.view_tours,name="view_tours"),
    url(r'^delete_tour/(?P<tour_id>[\d ]+)/$',
        apptours_views.delete_tour, name='delete_tour'),
    url(r'^update_apptour/(?P<tour_id>[\d ]+)/$',
        apptours_views.update_apptour, name='update_apptour'),

]

blog/urls.py
from django.conf.urls import url
from . import views as blog_views

urlpatterns = [
    url(r'^(?P<id>[\w-]+)/$', blog_views.blog, name='blog'),
    url(r'^comment/(?P<blog_id>[\w-]+)/$', blog_views.post_comment, name='comment'),
    url(r'^notification/(?P<id>[\w-]+)/$', blog_views.blog_notification, name='notification'),
    url(r'^subscribe/(?P<blog_id>[\w-]+)/$', blog_views.subscribe, name='subscribe'),
    url(r'^reply/(?P<blog_id>[\w-]+)/(?P<comment_id>[\w-]+)/$', blog_views.comment_reply, name='reply'),
]

source/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from courses import views as course_views
from registration.backends.default.views import RegistrationView
from users.forms import AddUser

urlpatterns = [
    url(r'^$', user_views.home, name='home'),
    url(r'^ourteam/$', user_views.ourteam, name='ourteam'),
    url(r'^about/$', user_views.about, name='about'),
    url(r'^contact/$', user_views.contact, name='contact'),
    url(r'^logout_view/$', user_views.logout_view, name='logout_view'),
    url(r'^thanks$',course_views.thanks, name='thanks'),
    url(r'cancel$', course_views.cancel, name='cancel'),	
    url(r'^admin/', admin.site.urls),
    url(r'^courses/', include('courses.urls')),
    url(r'^apptours/', include('apptours.urls')),
    url(r'^forum/', include('forum.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^profile/', include('users.urls')),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('', include('social_django.urls', namespace='social')),
]

# Remove this in project deployment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apptours/models.py
from __future__ import unicode_literals
from users.models import UserProfile
from django.db import models

# Create your models here.


class Tour(models.Model):
    tour_name = models.CharField(max_length=50,unique=True)
    status = models.CharField(null=False, default="complete",max_length=10)
    tour_description = models.TextField(null=True, default="")
    tour_image = models.TextField(null=False, default="")
    tour_groups = models.CharField(default="users professors admin ",max_length=25)
    tour_create_date = models.DateTimeField()
    tour_update_date = models.DateTimeField(null=True, default=None)
    tour_users = models.ManyToManyField(UserProfile)


class Step(models.Model):
    element = models.CharField(max_length=50)
    placement = models.CharField(max_length=50)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=500)
    path = models.CharField(max_length=50)
    order = models.IntegerField()


class TourUsers(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    tour = models.ForeignKey(Tour, on_delete=models.CASCADE)
    visited = models.BooleanField(default=False)


def transform_tour_groups_field(input):
    if type(input) == dict:
        return "" \
            + ("user " if input.get("user") else "") \
            + ("professor " if input.get("professor") else "") \
            + ("admin " if input.get("admin") else "")
    elif type(input) == str:
        return {
            "user": True if "user" in input else False,
            "professor": True if "professor" in input else False,
            "admin": True if "admin" in input else False,
        }
    else:
        return None

apptours/views.py
from django.http import HttpResponse
from models import Tour, Step, transform_tour_groups_field, TourUsers
from users.models import UserProfile
import json
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test, login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from datetime import datetime



# Create your views here.


@login_required
def get_tours(request):
    user_type = get_user_type(user=request.user._wrapped)
    tours = Tour.objects.filter(status="complete",tour_groups__contains=user_type).values()
    response = []
    for tour in tours:
        tour["tour_groups"] = transform_tour_groups_field(str(tour["tour_groups"]))
        tour["tour_create_date"] = tour["tour_create_date"].strftime('%Y-%m-%dT%H:%M:%S')
        tour["tour_update_date"] = None if tour.get("tour_update_date") is None \
            else tour["tour_update_date"].strftime('%Y-%m-%dT%H:%M:%S')
        tour["visited"] = tour_visited_by_user(user_id=request.user._wrapped.id,tour_id=tour.get("id"))
        temp_tour = {k:v for k,v in tour.items()}
        temp_steps = []
        tour['steps'] = Step.objects.filter(tour=tour['id']).values()
        for temp_step in tour['steps']:
            temp_steps.append({k:v for k,v in temp_step.items()})
        temp_tour['steps'] =  temp_steps
        response.append(temp_tour)
    #ensure order of first unvisited second create date
    unvisited = list(filter(lambda i: i.get("visited") == False, response))
    unvisited_sorted = sorted(unvisited,key=lambda i: i.get("tour_create_date"), reverse=True)
    visited = list(filter(lambda i: i.get("visited") == True, response))
    visited_sorted = sorted(visited, key=lambda i: i.get("tour_create_date"), reverse=True)
    return HttpResponse(json.dumps(unvisited_sorted + visited_sorted))


def tour_visited_by_user(user_id, tour_id):
    tour_users = TourUsers.objects.filter(tour__id=tour_id,user__id=user_id)
    if len(tour_users)>0:
        return tour_users[0].visited
    else:
        return False


def get_user_type(user):
    if user.is_professor:
        return "professor"
    elif user.is_site_admin:
        return "admin"
    else:
        return "user"


@login_required
def mark_tour_as_visited(request, tour_id):
    user_id = request.user._wrapped.id
    tour_user = TourUsers.objects.filter(tour__id=tour_id,user__id=user_id)[0]
    updated_tour_user = TourUsers(
        id=tour_user.id,
        tour_id=tour_id,
        user_id=user_id,
        visited=True
    )
    updated_tour_user.save(force_update=True)
    response = "tour_user with tour_id %s and user_id %s is marked as viewed"%(tour_id,user_id)
    return HttpResponse(response)


@user_passes_test(lambda user: user.is_site_admin)
def create_apptour(request):
    return render(request, "app_tour/create_app_tour.html")


@user_passes_test(lambda user: user.is_site_admin)
def create_tour(request):
    if request.method == 'POST':
        post_text = json.loads(request.POST.get('app_tour'))
        if post_text.get("tour").get("id") is not None:
            update_existing_apptour(post_text=post_text)
        else:
            create_new_apptour(post_text=post_text)
        return redirect(reverse('create_apptour'))


def update_existing_apptour(post_text):
    #check to se if creating a new apptour or making a previously incomplete(i.e., saved) apptour complete
    existing_tour = Tour.objects.get(id=post_text.get("tour").get("id"))
    if existing_tour.status == "incomplete":
        #creating new tour from existing saved tour
        if post_text.get("tour").get("status") == "incomplete":
            print("saving saved tour")
        else:
            print("creating saved tour")
        tour = Tour(
            tour_name=post_text.get("tour").get("tour_name"),
            id=post_text.get("tour").get("id"),
            status=post_text.get("tour").get("status"),
            tour_description=post_text.get("tour").get("tour_description"),
            tour_groups=transform_tour_groups_field(post_text.get("tour").get("tour_groups")),
            tour_image=post_text.get("tour").get("tour_image"),
            tour_create_date=datetime.now()
        )
        tour.save(force_update=True)
    else:
        #updaing an existing tour
        if post_text.get("tour").get("status") == "incomplete":
            print("saving previously created tour")
            print("warning: the previoius version and the newer version will both be unaccessable to the users at this time")
        else:
            print("updating previously created tour")
        tour = Tour(
            tour_name=post_text.get("tour").get("tour_name"),
            id=post_text.get("tour").get("id"),
            status=post_text.get("tour").get("status"),
            tour_description=post_text.get("tour").get("tour_description"),
            tour_groups=transform_tour_groups_field(post_text.get("tour").get("tour_groups")),
            tour_image=post_text.get("tour").get("tour_image"),
            tour_create_date=existing_tour.tour_create_date,
            tour_update_date=datetime.now()
        )
        tour.save(force_update=True)
    Step.objects.filter(tour__id=post_text.get("tour").get("id")).delete()
    for step in post_text.get("steps"):
        step = Step(
            placement=step.get('placement'),
            title=step.get('title'),
            element=step.get('element'),
            content=step.get('content'),
            path=step.get('path'),
            order=step.get('order'),
            tour=tour
        )
        step.save(force_insert=True)


def create_new_apptour(post_text):
    if post_text.get("tour").get("status") == "incomplete":
        print("saving new tour")
    else:
        print("creating new tour")
    tour = Tour(
        tour_name=post_text.get("tour").get("tour_name"),
        status=post_text.get("tour").get("status"),
        tour_description=post_text.get("tour").get("tour_description"),
        tour_groups=transform_tour_groups_field(post_text.get("tour").get("tour_groups")),
        tour_image=post_text.get("tour").get("tour_image"),
        tour_create_date=datetime.now()
    )
    tour.save(force_insert=True)
    connect_apptour_to_users(tour_id=tour.id)
    for step in post_text.get("steps"):
        step = Step(
            placement=step.get('placement'),
            title=step.get('title'),
            element=step.get('element'),
            content=step.get('content'),
            path=step.get('path'),
            order=step.get('order'),
            tour=tour
        )
        step.save(force_insert=True)


def connect_apptour_to_users(tour_id):
    all_user_ids = [val.get("id") for val in UserProfile.objects.values("id")]
    for user_id in all_user_ids:
        print("making TourUsers object with user id %s and tour id %s"%(user_id,tour_id))
        tour_users = TourUsers(user_id=user_id, tour_id=tour_id)
        tour_users.save()


@user_passes_test(lambda user: user.is_site_admin)
def view_tours(request):
    tours = Tour.objects.filter(status="complete")
    for tour in tours:
        tour.tour_groups = transform_tour_groups_field(str(tour.tour_groups))
    saved_tours = Tour.objects.filter(status="incomplete")
    for tour in saved_tours:
        tour.tour_groups = transform_tour_groups_field(str(tour.tour_groups))
    return render(request, "app_tour/tour_views.html", {"tours":tours,"saved_tours":saved_tours})


@user_passes_test(lambda user: user.is_site_admin)
def delete_tour(request, tour_id=None):
    instance = Tour.objects.get(id=tour_id)
    instance.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@user_passes_test(lambda user: user.is_site_admin)
def update_apptour(request, tour_id=None):
    instance = Tour.objects.get(id=tour_id)
    instance.tour_groups = transform_tour_groups_field(str(instance.tour_groups))
    return render(request, "app_tour/create_app_tour.html", {"instance":instance})

templates/app_tour/app_tour_modal.html
<!-- Modal -->
  <div class="modal fade" id="app_tour_display_modal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3>App Tours</h3>
        </div>
        <div class="modal-body">
          <div style="display:none;" id="display_all_apptours">
            <a id="view_single_tour">see one tour at a time</a>
            <p>Click on the collapsible panel to view the tour and close it.</p>
            <div class="panel-group" id="all_displayed_tours">
            <!--dynamically add tours-->
            </div>
          </div>
          <div style="display:block;" id="display_single_apptour">
            <a id="view_all_tours">see all tours</a>
            <h3 id="single_display_tour_name" class="panel-title">
            </h3>
            <div>
              <h5 id="single_display_tour_create_date">
              </h5>
              <h5 id="single_display_tour_visited">
              </h5>
              <p id="single_display_tour_description">
              </p>
              <div class="tour_image img-responsive">
                <img id="single_display_tour_image" src="">
              </div>
              <button class="btn-primary btn" id='display_previous_tour'>see previous tour</button>
              <button class="btn-primary btn" id='display_next_tour'>see next tour</button>
              <button class="btn-success btn" id='apptour_single'>start tour</button>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

templates/app_tour/create_app_tour.html
{% extends 'base.html' %}

{% block content %}

{% load staticfiles %}

<script>
  {% if instance %}
  tour_groups={}
  {% for k,v in instance.tour_groups.items%}
  tour_groups.{{k}}= "{{v}}" == "True" ? true : false;
  {%endfor%}

  var instance = {};
  instance.tour = {
        tour_name: "{{instance.tour_name}}",
        id:{{instance.id}},
        tour_description:"{{instance.tour_description}}",
        tour_image:"{{instance.tour_image}}",
        tour_groups:tour_groups,
  };
  instance.steps = []
  {% for step in instance.step_set.all %}
  var add_step ={
        title:"{{step.title}}",
        content:"{{step.content}}",
        path: "{{step.path}}",
        element: "{{step.element}}",
        placement: "{{step.placement}}",
        order: "{{step.order}}"
      };
  instance.steps.push(add_step);
  {% endfor %}
  {% else %}
  var instance = null;
  {% endif %}
</script>


<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<br/>
<a style="float:right; margin-right:2em;" href="{% url 'view_tours' %}" ><button type="button" id="view_tours" class="btn btn-primary">View Existing Tours</button></a>
<br/>
<div class="container">
  <div class="row">
    <div class="col-sm-10">
      <form action="/apptours/create_tour/" method="POST" id="post-form">
          {% csrf_token %}
        <div class="form-group">
          <label for="tour_name">Tour Name:</label>
          <input type="name" class="form-control" id="tour_name">
        </div>
        <div class="form-group">
          <label for="tour_description">Tour Description:</label>
            <textarea type="name" class="form-control" id="tour_description"></textarea>
        </div>
        <div class="form-group">
          <label for="tour_image">Tour Image:</label>
          <input type="file" class="form-control" id="tour_image">
          <button type="button" id="tour_image_reset" class="btn btn-default">Reset Image</button>
          <div class="tour_image"><img id="tour_image_display" src=""></div>
        </div>
        <div id="tour_group" class="form-group">
          <label for="tour_groups">Tour Groups:</label>
          <label class="checkbox-inline"><input id="tour_group_user" type="checkbox" value="">Users</label>
          <label class="checkbox-inline"><input id="tour_group_admin" type="checkbox" value="">Administrator</label>
          <label class="checkbox-inline"><input id="tour_group_professor" type="checkbox" value="">Professors</label>
        </div>
        <div>
          <label>Steps:</label>
          <div id="steps">
            <button type="button" class="btn btn-primary">Step <span class="badge">1</span></button>
              <div id="step1">
                <div class="form-group">
                    <label >Title:</label>
                    <input class="form-control" id="step1_title">
                  </div>
                <div class="form-group">
                    <label >Content:</label>
                    <textarea class="form-control" id="step1_content"></textarea>
                  </div>
                <div style="display: none;" class="form-group">
                    <label >Placement:</label>
                    <select  id="step1_placement" class="form-control">
                        <option value="top">Top</option>
                        <option value="bottom">Bottom</option>
                        <option value="left">Left</option>
                        <option value="right">Right</option>
                    </select>
                </div>
                <div style="display: none;" class="form-group">
                    <label>Path:</label>
                    <input class="form-control" id="step1_path">
                  </div>
                <div style="display: none;" class="form-group">
                    <label >Element:</label>
                    <input class="form-control" id="step1_element">
                  </div>
                 <div  style="display: none;" class="form-group">
                    <label >Order:</label>
                      <input readonly value="1" class="form-control" id="step1_order">
                 </div>
                  <pre>Path:  <span id="step1_path_display"></span>  Element: <span id="step1_element_display"></span>   Position: <span id="step1_placement_display"></span>    Order: <span id="step1_order_display">1</span></pre>
                  <a class="app_tour_iframe_link" href="">view iframe of site to find elements</a>
            </div>
          <!--where steps are dynamically added-->
          </div>
            <!--form validation goes here-->
            <div style="display:none;" id="apptour_error_box" class="alert alert-danger">
                <strong>Form Invalid:</strong>
                <ul id="apptour_form_errors"></ul>
            </div>
           <button type="button" id="add_step" class="btn btn-primary">Add Step</button>
           <button type="button" id="remove_step" class="btn btn-danger">Remove Last Step</button>
           <button type="button" id="save_tour" class="btn btn-info">Save Tour Progress</button>
        </div>
        <button type="button" id="submit_apptour" class="btn btn-success btn-block">Submit</button>
      </form>
    </div>
  </div>
</div>


<!-- Modal IFrame -->
<div  id="app_tour_iframe_modal" class="modal fade" role="dialog">
  <div style="width:95%; height:95%;" class="modal-dialog">
      <div style="width:95%; height:95%;" class="modal-content">
        <button type="button btn-danger" class="close" data-dismiss="modal">CLOSE</button>
        <h4 class="modal-title">Select Tour Elements</h4>
        <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#iframe_directions">Directions</button>
          <div id="iframe_directions" class="collapse">
            To select an element to bind the app tour step to, navigate to the location
            on this site where the element lies and double click the desired element.
            When you double click an element a popup will show from the desired element.
            The popup will ask you to confirm the chosen element. This tracks three items:
            The css path of the chosen element, the page path, and the side of the element that
            is used to bind the app tour step to. If you wish to choose another element just double
            click anwhere else than the confirm button and the popup will go away for you to choose another element;
            however, if you wish to choose this element, double click the confirm button.
          </div>
        <iframe id="app-tour-iframe" style="width:100%; height:90%;"src="/"></iframe>

        <div style="height:100px;" class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
        </div>
      </div>
  </div>
</div>


<!-- Modal Confirm Submit -->
  <div class="modal fade" id="modal_confirm" role="dialog">
    <div class="modal-dialog">
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Confirm you Want to Add This Tour</h4>
        </div>
        <div class="modal-body">
          <div>
            <div>
              <h4>Tour Name:</h4><p id="confirm_apptour_tourname"></p>
                Tour Description:<p id="confirm_apptour_tour_description"></p>
                Tour Groups: <p id="confirm_apptour_tour_groups"></p>
                Tour Image:<br/><div class="tour_image"><img id="confirm_apptour_tour_image" src=""></div>
            </div>
            <div id="confirm_apptour_steps">
              <!--add steps to display dynamically-->
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-info" id="confirm_apptour_try_tour">Try Tour</button>
          <button type="button" id="confirm_apptour_submit" class="btn btn-primary" data-dismiss="modal">Confirm Submit</button>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/app_tour/tour_views.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}



<div class="container">
  <h2>Open Build Tours</h2>
  <button style="float:right; margin-right:2em;" type="button" id="view_saved_tours" class="btn btn-info">View Saved Tours</button>
  <button style="float:right; margin-right:2em;display:none;" type="button" id="view_complete_tours" class="btn btn-primary">View Completed Tours</button>
  <br/>
  <p>Click on the collapsible panel to view the tour and close it.</p>
  <div class="panel-group" id="complete_tours_list">
    {% for tour in tours %}
    <div class="panel panel-default">
      <a data-toggle="collapse" href="#collapse{{tour.id}}">
        <div class="panel-heading">
        <h3 class="panel-title">
          {{tour.tour_name|upper}}
        </h3>
        </div>
      </a>
      <div id="collapse{{tour.id}}" class="panel-collapse collapse">
        <div class="panel-body">
          <br/>
          <h5>
          Create Date: {{tour.tour_create_date}}
          </h5>
          <h5>Tour Description:</h5><p>{{tour.tour_description}}</p>
          <h5>
          Tour Groups:
            {%for tour, group in tour.tour_groups.items%}
            {%if group%}
              {{tour}}
            {%endif%}
            {%endfor%}
          </h5>
          {% if tour.tour_image != '' %}
          Tour Image:<br/>
          <div class="tour_image img-responsive"><img src="{{tour.tour_image}}"></div>
          {% endif %}
          <h4>Tour Steps:</h4>
          <br/>
          {% for step in tour.step_set.all %}
          <h5>Title:</h5> <p style='font-family: "Times New Roman", Times, serif; font-size:1em;'>{{step.title}}</p>
            <br/>
          <h5>Content:</h5> <p style='font-family: "Times New Roman", Times, serif; font-size:1em;'>{{step.content}}</p>
            <br/>
          <pre>Path: {{step.path}}   Element: {{step.element}}    Position: {{step.placement}}    Order: {{step.order}}</pre>
          {% endfor %}
          <a href="{% url 'update_apptour' tour.id %}"><button type="button"  class="btn btn-primary">Edit Tour</button></a>
          <a href="{% url 'delete_tour' tour.id %}" onclick='return confirm("Are you sure you want to delete {{tour.tour_name}} tour?");'><button onclick="confirmDelete('{{tour.tour_name}}','{{tour.id}}')" type="submit"  class="btn btn-danger">Remove Tour</button></a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="panel-group" id="saved_tours_list" style="display:none;">
    <p>Saved tours in progress to completion</p>
    {% for tour in saved_tours %}
    <div class="panel panel-default">
      <a data-toggle="collapse" href="#collapse{{tour.id}}">
        <div class="panel-heading">
        <h3 class="panel-title">
          {{tour.tour_name|upper}}
        </h3>
        </div>
      </a>
      <div id="collapse{{tour.id}}" class="panel-collapse collapse">
        <div class="panel-body">
          <br/>
          <h5>
          Saved Date: {{tour.tour_create_date}}
          </h5>
          <h5>Tour Description:</h5><p>{{tour.tour_description}}</p>
          <h5>
          Tour Groups:
            {%for tour, group in tour.tour_groups.items%}
            {%if group%}
              {{tour}}
            {%endif%}
            {%endfor%}
          </h5>
          {% if tour.tour_image != '' %}
          Tour Image:<br/>
          <div class="tour_image"><img src="{{tour.tour_image}}"></div>
          {% endif %}
          <br/>
          <h4>Tour Steps:</h4>
          <br/>
          {% for step in tour.step_set.all %}
          <h5>Title:</h5> <p style='font-family: "Times New Roman", Times, serif; font-size:1em;'>{{step.title}}</p>
            <br/>
          <h5>Content:</h5> <p style='font-family: "Times New Roman", Times, serif; font-size:1em;'>{{step.content}}</p>
            <br/>
          <pre>Path: {{step.path}}   Element: {{step.element}}    Position: {{step.placement}}    Order: {{step.order}}</pre>
          {% endfor %}
          <a href="{% url 'update_apptour' tour.id %}"><button type="button"  class="btn btn-primary">Edit Saved Tour</button></a>
          <a href="{% url 'delete_tour' tour.id %}" onclick='return confirm("Are you sure you want to delete {{tour.tour_name}} tour?");'><button onclick="confirmDelete('{{tour.tour_name}}','{{tour.id}}')" type="submit"  class="btn btn-danger">Remove Saved Tour</button></a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>



{% endblock %}